apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: my-go-app

build:
  artifacts:
    - image: my-go-app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: /app
          - src: "go.mod"
            dest: /app
          - src: "go.sum"
            dest: /app
          - src: ".air.toml"
            dest: /app

manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/istio-gateway.yaml
    - k8s/istio-virtualservice.yaml
    - k8s/istio-destinationrule.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: istio-ingressgateway
    namespace: istio-system
    port: 80
    localPort: 8080
